language: groovy
jdk:
- openjdk8
env:
  matrix:
  - LIB_GRADLE_VERSION=3.4.1 DEPLOY=true
  - LIB_GRADLE_VERSION=3.5.1
  - LIB_GRADLE_VERSION=4.0.1
  - LIB_GRADLE_VERSION=4.1
  - LIB_GRADLE_VERSION=4.2 DEPLOY=true
  - LIB_GRADLE_VERSION=4.2.1
  - LIB_GRADLE_VERSION=4.5 DEPLOY=true
  - LIB_GRADLE_VERSION=4.5.1
  - LIB_GRADLE_VERSION=4.8 DEPLOY=true
  - LIB_GRADLE_VERSION=4.8.1
  - LIB_GRADLE_VERSION=4.10.2
  - LIB_GRADLE_VERSION=7.2 DEPLOY=true
  - LIB_GRADLE_VERSION=8.4 DEPLOY=true
  global:
    # The next declaration is the encrypted gradlePublishKey
  - secure: tzRoJbjW38G0YcSRuf53+koo/ZixIrA1vHJ9StOfafZOJzKyoASkbFa2EpUKmp3CXBWvUSTVo59j7ywUSyWW+L+G+CRnYqkDTktySJ/LAHjR0CH5dJCUodwcwtZkBje/RQZ//ZuPO2I7wY/aqHfj/E8pg2h9Y+nOd2v9R904/5b5gck9nM1Tr74YE2dJDm3h0QKrMqx6/oT7KVTWQpTNeLxcdrdNn5yxllqn4YDF70gEksoSuJeFR2l5lwSlTTseKI7Q7mGYI1Tg/PSZoxlPz3DGFmSe+9sewRnN9ZnjQDEY06/GmrGQHGv9MV1azvenlFHrt9lIbHnEo0GBqxNpeFfMd4+B9oeEmL8roapNSq0TCgVvOzda/G5KyY8TgLEi+k7WrZaWGvbW+AorU5ntenWEzSWz3b5lpwnwXxrPyyRnaKd3R5mRYj+LL10hlHAiWpvXn+v6ptD2OunE6l3JEm+wln+6wZjJBqBhl1jsv3LOd5siezFGqqOzC6FN6UgkTZqsgMfROzoqklFv3Ko8fU4e6oo9VzI/cJGcFHFO4M+dOHyYZbKl8hfvi1Bf44UpYo914sdwmWGIAZ8J6V2xtCqTnyN1bi/EQuKAkE2400laduCt/rnGyR8IefcM6iFxjufR5jCXpXBhbQ0cQ//pUT0eW4ssjqKvt9RrJmt/Mew=
    # The next declaration is the encrypted gradlePublishSecret
  - secure: Z9rf5KL9USpw7n05xJ+6hLSxgwgepXEw+f5ZwUx9cqKr/TdjSHimjHaGrYizBjjqXxa5fXwoAXmh8dvxyp0khKvtRrhN9JU2WRJt/Kweu/hrW5F+EkrzGBIeDoAtQvLqwOVQH5usRxVBHz3OEcwiFZKldcnvpMaCJcPVpO3YGfDVoX9+dlRYJRAPYFH0LsxJFiZYFzDN3x+eeVfnucgwXkRco+8R04gJ/LGF4rQhn6FupQWk8AepvnmAhAg1HhEvWUSwmD/sQ86xHw9WqMX/PxdSb21tM8VYrj6+ZGFh8C1g7NAVkOSFQjjYSqHb1wDUBHmxMvyUw3KZiBkhFjweTpuxoPHVwbQqhFKH/WXYtnuYKoIlebR7c7CtZ11Xp9ba98PA3ADIzRvOQrPn42iyvXvqg78AROb2OtOa639znxu3lckDoU3PH/n5jHmy9awlwEZSoNkw0dM+RtJGO+X4l1kPQGoOMZVjlA/vvkfhHJqCOwZHX8O9bW/yv328jmgRMdTo8uTV9IrzqgJJgg+v7iEJ1DpBph46dFn7zPliUQWXDDCxXqXSy9V1BVFB1fTKzP9fosrbCCu3CjaTdiXBdPvKpjLE+gVJRt12rzQOKAzOcIt5GtJIkkElo2v3ofSJPdx9aET/nYJepiKW5NMxoPkq/HsMRbeQiyEs3WXqaCQ=
before_install:
- echo $TRAVIS_TAG
- sudo apt-get -qq update
- sudo apt-get install -y fakeroot
install:
  - gradle wrapper
  # upload to '../repo'
  - "./gradlew publish"
deploy:
  provider: releases
  api_key:
    secure: MMB1giHuop1R9hws7WsnB5EFmep7lW7DjkpkR6t9ifUAUhIOPDMin3L1YG5fpRw8L7xOuGytCQphaQt+O1FhJoRZcPeoZHPVF3AEGYcUYzbpWUREhaAewBP/47CP95wckfEWdCzRbzwNhxaJQdidmg4P2g2Rt+yVZUQ1nOgXuJk+eHd3vczHEOuSZXa2CuVCmQP+Kfb8YRuRpLP//HAZ4s51IbLGDa4urgwcx06IEfrc/PN8umJNdjWAMdNpP4tkc2VvH17onb81wSc/esYjEprRiAWTuKLUXzTPz53J0VFhMelEAjLtRVP84KNGzCMzBMOMqs+Am9Fl3HFNf9MSoSvBCdXWVFlWudarvEt3kg9TNeFNAkaV40t62OIIALOGm2sOsg1MGaCbOCdfz12IZzRAyalnhcCTAqJjvfPNleAMz7sDxULzUqrjvPFROPWFPNYStDMNPYaq6AAZqPp6rPiP34b/owcSH5a2sSbhz6zdVcC8SknCvp9QNMNTaoJQIWVQKEoxYkZrkc1wibymXasciVR2ejNzBG5CDYWLLId3Uu4RDSaLWXZtAE9hKvbP0D/WNELRz2JKNVICEysPGdDB2HQTeJ/ynKdagfN4KWEDa5q1dgnUe+qMlo3XshCmdTMX3+rOlZi6ovpa90vTKKW3q5hxC/KMiy9LdA7Ag4k=
  file_glob: true
  file: "./build/libs/SetupBuilder-*"
  skip_cleanup: true
  overwrite: true
  on:
    repo: i-net-software/SetupBuilder
    tags: true
    condition: $DEPLOY = true
after_deploy:
  - "./gradlew publishPlugin"
